algorithm: stssl_fixmatch
save_dir: ./runs/submission/eurosat/
save_name: stssl_fixmatch10
resume: False #True
load_path: null
overwrite: True
use_tensorboard: False
use_wandb: True
epoch: 200
num_train_iter: 204800
num_log_iter: 256
num_eval_iter: 2048
patience_iters: 32768
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 5120
num_labels: 10
uratio: 1
ema_m: 0.999
hard_label: True
T: 0.5
p_cutoff: 0.95
ulb_loss_ratio: 1.0
distill_loss_type: mse
lambda_d: 0.01
img_size: 32
crop_ratio: 0.875
optim: AdamW
lr: 5e-05
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: False
clip: 0.0
use_cat: True
net: early_fusion_vit_small_patch2_32
feat_dim: 384
net_from_name: False
data_dir: ./data
dataset: eurosat
metadata_file: eurosat_meta.yaml
train_sampler: RandomSampler
num_classes: 10
multilabel: False
num_workers: 4
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10007
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch2_32_mlp_im_1k_32.pth
