algorithm: cdmad
save_dir: ./runs/debug
save_name: cdmad
resume: False #True
load_path: null 
overwrite: True
use_tensorboard: False
use_wandb: True
epoch: 1
num_train_iter: 64000
num_eval_iter: 2000
patience_iters: 16000
debias_start_iter: 2000
p_cutoff: 0.0
num_log_iter: 100
num_labels: 100
batch_size: 64
eval_batch_size: 512
ulb_loss_ratio: 1.0
uratio: 7
ema_m: 0.999
crop_ratio: 0.875
img_size: 128
optim: AdamW
lr: 1e-4
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: vit_small_patch16_128 # wrn_28_2
net_from_name: False
data_dir: ./data
pt_data_dir: bigearthnet_rgb_pt_f16
dataset: bigearthnet
train_sampler: RandomSampler
num_classes: 43
multilabel: True
num_workers: 8
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: False
dist_url: tcp://127.0.0.1:10008
dist_backend: nccl
gpu: 0
use_pretrain: True
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
