algorithm: cap
amp: false
batch_size: 64
clip: 0.05
crop_ratio: 0.875
data_dir: ./data
dataset: bigearthnet
disable_torch_grad_focal_loss: true
dist_backend: nccl
dist_url: tcp://127.0.0.1:10008
ema_m: 0.999
ema_t: 0.999
epoch: 1
eps: 1e-8
eval_batch_size: 512
gamma_neg: 4
gamma_pos: 1
gpu: 0
img_size: 128
layer_decay: 1.0
load_path: null
lr: 1e-4
momentum: 0.9
multilabel: true
multiprocessing_distributed: false
neg_per: 1.0
net: vit_small_patch16_128
net_from_name: false
num_classes: 43
num_eval_iter: 2000
num_labels: 0.01
num_log_iter: 100
num_train_iter: 64000
num_workers: 8
optim: AdamW
overwrite: true
patience_iters: 16000
pos_per: 1.0
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
pseudolabel_from_ema: true
pt_data_dir: null
rank: 0
resume: false
save_dir: runs/bigearthnet/
save_name: cap0.01
seed: 0
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_asl: true
use_cat: true
use_pretrain: true
use_tensorboard: false
use_wandb: true
weight_decay: 0.0005
world_size: 1
