T: 0.5
algorithm: freematch
amp: false
batch_size: 64
clip: 0.0
crop_ratio: 0.875
data_dir: ./data
dataset: bigearthnet
dist_backend: nccl
dist_url: tcp://127.0.0.1:10068
ema_m: 0.999
ema_p: 0.999
ent_loss_ratio: 0.001
epoch: 1
eval_batch_size: 512
gpu: 0
hard_label: true
img_size: 128
layer_decay: 1.0
load_path: null
lr: 1e-4
momentum: 0.9
multilabel: true
multiprocessing_distributed: false
net: vit_small_patch16_128
net_from_name: false
num_classes: 43
num_eval_iter: 2000
num_labels: 0.01
num_log_iter: 100
num_train_iter: 64000
num_workers: 8
optim: AdamW
overwrite: true
patience_iters: 16000
pretrain_path: https://github.com/microsoft/Semi-supervised-learning/releases/download/v.0.0.0/vit_small_patch16_224_mlp_im_1k_224.pth
pt_data_dir: null
rank: 0
resume: false
save_dir: runs/bigearthnet/
save_name: freematch0.01
seed: 0
sup_warmup_iters: 2000
train_sampler: RandomSampler
ulb_loss_ratio: 1.0
uratio: 7
use_cat: true
use_pretrain: true
use_quantile: false
use_tensorboard: false
use_wandb: true
weight_decay: 0.0005
world_size: 1
